// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	listProjects: () => typedError<Model[], string>(__TAURI_INVOKE("list_projects")),
	createProject: (name: string, path: string) => typedError<Model, string>(__TAURI_INVOKE("create_project", { name, path })),
};

/* Types */
export type Model = {
	id: number,
	name: string,
	path: string,
	created_at: string,
	updated_at: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

