// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommitData } from "./CommitData";

/**
 * Events sent from the instrumented browser (`@submarine/react`) to the
 * Tauri backend via Socket.IO.
 */
export type ClientToServer = { "type": "commit", "data": CommitData };
