// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentNode } from "./ComponentNode";
import type { RenderPhase } from "./RenderPhase";

/**
 * Data for a single React commit event.
 */
export type CommitData = { 
/**
 * The phase that triggered this commit.
 */
phase: RenderPhase, 
/**
 * Parsed component tree for this root.
 */
tree: ComponentNode, 
/**
 * Timestamp of the commit.
 */
timestamp: number, };
