// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Component type classification matching React fiber tags.
 */
export type ComponentKind = "function" | "class" | "host" | "memo" | "forward-ref" | "suspense" | "context" | "fragment" | "root" | "other";
