// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ComponentKind } from "./ComponentKind";
import type { Timings } from "./Timings";

/**
 * A parsed React component node in the tree.
 */
export type ComponentNode = { 
/**
 * Stable ID persisted across re-renders.
 */
id: number, 
/**
 * Display name (e.g. "App", "Button", "div").
 */
name: string, 
/**
 * Component type classification.
 */
kind: ComponentKind, 
/**
 * Current props snapshot.
 */
props: Record<string, unknown>, 
/**
 * Render timing (only available with React Profiler).
 */
timings: Timings | null, 
/**
 * Whether this fiber rendered in the last commit.
 */
rendered: boolean, 
/**
 * Whether React Compiler memo cache is active.
 */
memoized: boolean, 
/**
 * Associated DOM element tag name, if any.
 */
hostTag: string | null, 
/**
 * Depth in the component tree (0 = root).
 */
depth: number, 
/**
 * Children component nodes.
 */
children: Array<ComponentNode>, };
