// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The phase that triggered a React render (matches bippy's `RenderPhase`).
 */
export type RenderPhase = "mount" | "update" | "unmount";
